version: '3.7'

services:
  office-chain:
    build:
      context: .
      dockerfile: Dockerfile
    image: office-chain-image
    container_name: office-chain-container
    restart: unless-stopped
    ports:
      - "4300:4200"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    command: sh -c "npm start"
    working_dir: /home/node/app

volumes:
  node_modules:
