version: '3.7'

services:
  office-chain:
    build:
      context: .
      dockerfile: Dockerfile
    image: office-chain-image
    container_name: office-chain-container
    restart: unless-stopped
    ports:
      - "4300:4200"
    command: sh -c "npm start"
